MONGODB_HOST: mongodb-{{ env }}.fineshit.shop #mongodb-dev.fineshit.shop
REDIS_HOST: redis-{{ env }}.fineshit.shop
CATALOGUE_HOST: catalogue-{{ env }}.fineshit.shop
CART_HOST: cart-{{ env }}.fineshit.shop
USER_HOST: user-{{ env }}.fineshit.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.fineshit.shop
MYSQL_HOST: mysql-{{ env }}.fineshit.shop
SHIPPING_HOST: shipping-{{ env }}.fineshit.shop
PAYMENT_HOST: payment-{{ env }}.fineshit.shop